### PR TITLE
Esp32 support

### PR DESCRIPTION
**Pull request by baggior**
issue #46

### CODE REVIEW

**Comment by arkhipenko** [comment]
Pushed v2.6.0 into the "testing" branch with ESP32 support. Could you please test?
https://github.com/arkhipenko/TaskScheduler/tree/testing

**Comment by baggior** [comment]
I don't agree there are some bug and compilation errors due to bad merge of my changes

can I help you on merge?
