### ISSUE TITLE
Could not compile 3.4, but works with 3.3

### ISSUE THREAD

**Issue by ellogwen** [arkhipenko/TaskScheduler#128]
I created a project with 3.3, but after updating to 3.4 I could not compile it anymore:

```
error: no matching function for call to 'Task::set(long unsigned int, int, Device::setup()::<lambda()>)'
```

I could not find anything in the release notes, that this update would break backward compatibility

**Comment by ellogwen** [comment]
Somehow platformio / vscode messed up my header files. Rebootet and then compilation worked again. Sorry.
